### ISSUE TITLE
StringCallback IO异常导致无法编译通过

### ISSUE THREAD

**Issue by GanTongZhen** [Tamsiree/RxTool#105]
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for com/lzy/okgo/callback/StringCallback
Error:com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.io.IOException: Failed to find byte code for com/lzy/okgo/callback/StringCallback
Error:java.lang.RuntimeException: java.io.IOException: Failed to find byte code for com/lzy/okgo/callback/StringCallback
Error:java.io.IOException: Failed to find byte code for com/lzy/okgo/callback/StringCallback

**Comment by yonkylin** [comment]
我也遇到了，这样改了就好了https://blog.csdn.net/CSDN_LuoYang/article/details/79870745
