### ISSUE TITLE
RxCrashTool不抛出异常,应用也不退出

### ISSUE THREAD

**Issue by JinZhao93** [Tamsiree/RxTool#109]
RxFileTool中如果sd卡不可用
![image](https://user-images.githubusercontent.com/13034624/39033721-ff1872ec-44a5-11e8-9b5e-531d6c2eb871.png)

RxCrashTool中到这步就停住了，这个时候，应用就挂住不报错了。
![image](https://user-images.githubusercontent.com/13034624/39033651-a72826ea-44a5-11e8-9e31-fd33ee316748.png)

至于为啥sd卡会不可用，我是引入
implementation 'io.fotoapparat.fotoapparat:library:2.2.0'
后发现的，具体原因还没了解，总之可能出现应用退出不了也不报异常的情况。

**Comment by JinZhao93** [comment]
原因在于
implementation 'io.fotoapparat.fotoapparat:library:2.2.0'库中
在读文件的<user-permission>中添加了android:maxSdkVersion="18"
导致与主库合并后获取不到读取权限。。。

**Comment by Tamsiree** [comment]
已更新RxCrashTool，更新到最新版本试试
