### ISSUE TITLE
RxQRCode生成的二维码的边距边距空白太大了

### ISSUE THREAD

**Issue by T-mans** [Tamsiree/RxTool#124]
建议预留设置的参数，个人对函数进行了轻微的修改，满足了需求，但是希望可以放在库里面
public static Bitmap creatQRCode(CharSequence content, int QR_WIDTH, int QR_HEIGHT, int backgroundColor, int codeColor) {
        Bitmap bitmap = null;

        try {
            if (content == null || "".equals(content) || content.length() < 1) {
                return null;
            }

            Hashtable<EncodeHintType, String> hints = new Hashtable();
            hints.put(EncodeHintType.CHARACTER_SET, "utf-8");
            hints.put(EncodeHintType.MARGIN, "1");//个人添加的一句
            BitMatrix bitMatrix = (new QRCodeWriter()).encode(content + "", BarcodeFormat.QR_CODE, QR_WIDTH, QR_HEIGHT, hints);
            int[] pixels = new int[QR_WIDTH * QR_HEIGHT];

            for (int y = 0; y < QR_HEIGHT; ++y) {
                for (int x = 0; x < QR_WIDTH; ++x) {
                    if (bitMatrix.get(x, y)) {
                        pixels[y * QR_WIDTH + x] = codeColor;
                    } else {
                        pixels[y * QR_WIDTH + x] = backgroundColor;
                    }
                }
            }

            bitmap = Bitmap.createBitmap(QR_WIDTH, QR_HEIGHT, Bitmap.Config.ARGB_8888);
            bitmap.setPixels(pixels, 0, QR_WIDTH, 0, 0, QR_WIDTH, QR_HEIGHT);
        } catch (WriterException var11) {
            var11.printStackTrace();
        }

        return bitmap;
    }

**Comment by tydqcjj** [comment]
我也觉得边距太大了点，希望vondear大大能看到。加个设置参数。

**Comment by Tamsiree** [comment]
谢谢建议，已添加
