### ISSUE TITLE
value错误

### ISSUE THREAD

**Issue by potatolaver** [Tamsiree/RxTool#144]
C:\Users\Administrator\.gradle\cache\transforms-1\file-1.1\RxUI-v2.0.7.aar\420b7ba76b2cef03e28eff14124c6b9a\res\values\values.xml
    Error:(326, 5) error: <item> inner element must either be a resource reference or empty.
    Error:(344, 5) error: <item> inner element must either be a resource reference or empty.

326行 <item name="about_version_code" type="id">false</item>
344行 <item name="split" type="id">false</item>

**Comment by T-mans** [comment]
Android Studio 升级3.2后，gradle到4.6。同样是这个错误！

**Comment by T-mans** [comment]
https://stackoverflow.com/questions/51814939/error-on-changing-buildtoolsversion-of-project-in-android-studio

> @hasanghaforian the problem is that type="id" does not permit assigning values. AAPT2 might just ignore the value, where D8 might bug out. and even if it builds - it might not function as expected. 

> 

我怀疑和这个有关系！难道要禁止aapt2？觉得不太好啊，这样

**Comment by huangjian100** [comment]
我也有这个问题、请问解决了吗？一个时about_version type为id类型的false  一个时splite type 为id的false

**Comment by haijiaoqiufeng** [comment]
好像不解决问题了,考虑换库了.........

**Comment by huangjian100** [comment]
嗯、我不用这个库了，github上还有其他的库，比他的好多了
