### ISSUE TITLE
zxing包冲突

### ISSUE THREAD

**Issue by StoneXL** [Tamsiree/RxTool#148]
用exclude group: 'com.google.zxing'还是解决不了问题

**Comment by StoneXL** [comment]
![default](https://user-images.githubusercontent.com/18682525/42741656-ddaa6798-88e6-11e8-9927-8782d1e959fc.png)

**Comment by actor20170211030627** [comment]
implementation ('com.xx.xx:module:x.x.x') {//需要排除zxing的依赖
        exclude group: 'com.google.zxing', module: 'core'//排除zxing
    }
