### ISSUE TITLE
ActivityScanerCode 回调设计存在严重问题

### ISSUE THREAD

**Issue by jokerknight** [Tamsiree/RxTool#159]
1.静态的接口很容易造成内存泄漏
2.在A 界面打开ActivityScannerCode页面扫描之后在A界面进行页面Redirect后，没有办法关闭ActivityScannerCode了，因为没有页面的实例，且挡住了A界面，因为我的ScanListener是在A界面静态注册的。

**Comment by kinghom** [comment]
第二点我在ActivityScannerCode里面的回调方法加了finish()，不管扫码成功失败都finish掉。

**Comment by jokerknight** [comment]
@kinghom 我把ActivityScannerCode重写了，不用他的ScanListener，通过EventBus的方式通知出去就解决了。

**Comment by JoinBelieve** [comment]
你们的二维码扫描识别度高吗？
