### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by qfzhang123** [Tamsiree/RxTool#161]
在导入该库到项目里出现以下问题：
Could not resolve all dependencies for configuration ':RxDemo:debugRuntimeClasspath'.
Could not determine artifacts for com.android.support:support-fragment:27.1.1
Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/support/support-fragment/27.1.1/support-fragment-27.1.1.aar'.
Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/support/support-fragment/27.1.1/support-fragment-27.1.1.aar'.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
unable to find valid certification path to requested target

**Comment by Tamsiree** [comment]
更新到最新版本试试
