### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by ghost** [Tamsiree/RxTool#176]
Android resource compilation failed
Output:  D:\RnWorkSpace\AndroidJavaApp\UNGPay\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2226: error: <item> inner element must either be a resource reference or empty.
D:\RnWorkSpace\AndroidJavaApp\UNGPay\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2264: error: <item> inner element must either be a resource reference or empty.

Command: C:\Users\moz\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.0-4818971-windows.jar\91dfb3f981e916d9dd78f5ec474bfbde\aapt2-3.2.0-4818971-windows\aapt2.exe compile --legacy \
        -o \
        D:\RnWorkSpace\AndroidJavaApp\UNGPay\app\build\intermediates\res\merged\debug \
        D:\RnWorkSpace\AndroidJavaApp\UNGPay\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.0-4818971-windows Daemon #1

**Comment by huangjian100** [comment]
我已经重新导入gradle ，但、你的values代码依旧是错误的代码，更新不下来

**Comment by sunjiaxin** [comment]
> 我已经重新导入gradle，但，你的值代码依旧是错误的代码，更新不下来

你搞定了吗? 我也遇到这个问题了.
