### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by SummerMineJack** [Tamsiree/RxTool#191]
![image](https://user-images.githubusercontent.com/45996603/54532173-1b2e1a00-49c2-11e9-8fcb-4534aed45796.png)
![image](https://user-images.githubusercontent.com/45996603/54532189-25e8af00-49c2-11e9-9f38-a30a6db03b4a.png)

请问这种问题该怎么解决

**Comment by JanRisun** [comment]
需要更新代码了

**Comment by JanRisun** [comment]
需要更新代码了 <item name="about_version_code" type="id">false</item>

**Comment by JanRisun** [comment]
需要更新代码
<item name="about_version_code" type="id">
<item name="split" type="id">
不知道是不是这样

**Comment by JanRisun** [comment]
要不然你就降android studio 环境版本

**Comment by wjy000** [comment]
我也是同样的错误
