### ISSUE TITLE
华为p20系统9.0用toast弹几次稍微快点就不弹了

### ISSUE THREAD

**Issue by huluxia** [Tamsiree/RxTool#196]
华为p20系统9.0用toast弹几次稍微快点就不弹了。模拟器5.0测试没这个问题，小米4系统6.0也没问题。请问这是华为手机问题还是版本问题

**Comment by huluxia** [comment]
确定是这个库的问题，下载Toasty就没这个Bug

**Comment by Kylewwb** [comment]
怎么解决的，我也遇到过这个问题

**Comment by Tamsiree** [comment]
谢谢告知，已解决
