### ISSUE TITLE
扫码返回可能会引起异常

### ISSUE THREAD

**Issue by NightlyException** [Tamsiree/RxTool#200]
ActivityScanerCode文件下的decode方法在取消扫码返回上一级页面时引起handler空指针崩溃闪退，具体是在`Message message = Message.obtain(handler, R.id.decode_failed);
            message.sendToTarget();`中

**Comment by HeZhanHeng** [comment]
老铁，这个问题有解决办法么？

**Comment by NightlyException** [comment]
我直接新建一个Activity，复制它的代码，在引起空指针的地方前面加个判空
