### ISSUE TITLE
框架布局文件中的属性没有找到

### ISSUE THREAD

**Issue by fanzhiqiang123** [Tamsiree/RxTool#204]
C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\3c6c10bc0f6bb55675d3c3e92354a572\res\layout\card_item_picture.xml:11: error: attribute cardElevation (aka xxx.xxx.xxx:cardElevation) not found.

**Comment by fanzhiqiang123** [comment]
是引用     "com.github.vondear.RxTool:RxUI:2.3.9"  库时出现的，之前的版本没有这个问题

**Comment by luoyongzhe** [comment]
+1

**Comment by Tamsiree** [comment]
//(依赖RxUI库时，需要额外依赖 cardview 库)
      implementation 'com.android.support:cardview-v7:27.1.1'
