### ISSUE TITLE
AAPT: error: <item> inner element must either be a resource reference or empty。

### ISSUE THREAD

**Issue by JanRisun** [Tamsiree/RxTool#220]
问题出现原因：升级gradle插件导致
```
classpath 'com.android.tools.build:gradle:3.5.0'
```
解决方案：
https://blog.csdn.net/zsp_android_com/article/details/83062073
![image](https://user-images.githubusercontent.com/37615305/64685486-ac85d100-d4b9-11e9-837b-c4115856d25e.png)

大佬最近在忙没有时间维护了是么？

**Comment by Tamsiree** [comment]
最新版本已解决
