### ISSUE TITLE
二维码扫描位置不准确

### ISSUE THREAD

**Issue by BarkSheep** [Tamsiree/RxTool#221]
demo中将二维码放到扫描框中间扫不出来 将二维码放到手机屏幕中间识别率较高

**Comment by BarkSheep** [comment]
破案了 demo中的扫描框扫不出来 我将扫描框移到了屏幕中间 识别粗来了

**Comment by 903531306** [comment]
我也遇到同样的问题 便宜屏幕可以识别

**Comment by BarkSheep** [comment]
> 我也遇到同样的问题替换屏幕可以识别

把那个ui识别的框移到屏幕中间就可以了

**Comment by 903531306** [comment]
那你仓库代码是最新的吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "树皮羊"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上6:20
收件人: "Tamsiree/RxTool"<RxTool@noreply.github.com&gt;; 
抄送: "R.id.&amp;#x1F431;"<903531306@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Tamsiree/RxTool] 二维码扫描位置不准确 (#221)



 
我也遇到同样的问题替换屏幕可以识别
  
把那个ui识别的框移到屏幕中间就可以了

**Comment by Tamsiree** [comment]
谢谢告知，已修复
