### ISSUE TITLE
希望修复的地方

### ISSUE THREAD

**Issue by mayangyang-github** [Tamsiree/RxTool#224]
RxToast在Android 9 上,连点只弹出一次的问题
二维码扫描的扫描框焦点好像不在中间, 导致有人说扫描很慢, 其实只要把二维码放在扫描框偏下就能秒扫出来.
在全屏状态下, 华为P20的功能键(任务键, Home键, 返回键)会遮挡布局中的内容, 比如飞机选座.
联系人侧边快速导航中, 最列表顶部ABC的粘性头, 在华为P20pro 上是黑色的....
望改进~~~

**Comment by Tamsiree** [comment]
部分问题已修复，最近比较忙，请谅解
