### ISSUE TITLE
添加微信支付宝模块报错

### ISSUE THREAD

**Issue by lexluthors** [Tamsiree/RxTool#230]
添加这个implementation "com.github.tamsiree.RxTool:RxFeature:v2.4.1"模块报错。error: failed linking file resources. 你的res下的布局文件有问题。activity_scaner_code.xml:128: error: resource dimen/text_12  没有这个资源。

**Comment by Tamsiree** [comment]
这个库是我本人自己使用的工具库，因为近期没有使用支付模块的需求，因此没有及时更新

**Comment by lexluthors** [comment]
@Tamsiree 好吧。后续有空麻烦更新一下吧
