### ISSUE TITLE
ERROR: Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by lydlovezjr** [Tamsiree/RxTool#233]
<img width="772" alt="微信截图_20191230145343" src="https://user-images.githubusercontent.com/19246347/71571249-4e3a3800-2b14-11ea-9b29-ad515ae0f77c.png">

**Comment by TangYuLi** [comment]
+1

**Comment by chj233** [comment]
error: failed linking file resources.    activity_code_tool.xml:20: error: resource dimen/dp_55           sos

**Comment by chj233** [comment]
When integrating this plug-in, if you use support.v4 or support.v7, change the support library to Android x, otherwise you will not be able to merge the list. If you change it in Java code, remember to change it in the layout file

**Comment by Tamsiree** [comment]
最新版本已迁移至 AndroidX, 更新到最新版本试试

**Comment by FlatWang** [comment]
TangYuLi <notifications@github.com> 於 2020年1月16日 週四 10:39 寫道：
