### ISSUE TITLE
我整个人都傻了。。作者进来一下

### ISSUE THREAD

**Issue by huanghaoming** [Tamsiree/RxTool#246]
keyValues.put("timestamp", RxTimeTool.getCurrentDateTime("yyyy-MM-dd- HH:mm:ss"));

多了个杆号。。可以测一下再发布版本吗。。虽然开源给大家用，大家很感激，不过错误这么明显，又让使用者到处跳坑
keyValues.put("timestamp", RxTimeTool.getCurrentDateTime("yyyy-MM-dd HH:mm:ss"));

**Comment by huanghaoming** [comment]
忙了半天才追到这个地方来，不知道是不是故意的

**Comment by Tamsiree** [comment]
谢谢提醒，已改正，因为近来没有支付方面的需求，便没有完善。
