### ISSUE TITLE
Could not GET 'https://esri.bintray.com/arcgis/com/esri/arcgisruntime/arcgis-android/100.3.0/arcgis-android-100.3.0.pom'. Received status code 403 from server: Forbidden Disable Gradle 'offline mode' and sync project

### ISSUE THREAD

**Issue by Cazaea** [Tamsiree/RxTool#268]

**Comment by Cazaea** [comment]
通过下边方法可以解决问题，亲测有效：
https://stackoverflow.com/questions/65666902/arcgis-android-100-3-0-pom-says-forbidden

**Comment by Cazaea** [comment]
这个项目不知道是不是不维护了，Down下来，好多错误。
有个R.styleable.RxArcProgress_style_ui自定义空间引用错误；
还有大部分的非空判断及参数类型指定有问题；

**Comment by Cazaea** [comment]
压缩与解压功能异常。

**Comment by androidxu** [comment]
慎用！

**Comment by Cazaea** [comment]
各种问题

**Comment by yuqianglianshou** [comment]
将gradle中的     maven { url 'https://esri.bintray.com/arcgis'  }
    改为
maven{             url 'https://esri.jfrog.io/artifactory/arcgis'） }

原因是这个网站（https://esri.bintray.com/arcgis）用不了了

**Comment by yuqianglianshou** [comment]
> 这个项目不知道是不是不维护了，Down下来，好多错误。
> 有个R.styleable.RxArcProgress_style_ui自定义属性引用错误；
> 还有大部分的非空判断及参数类型指定有问题；

是啊，非空判断导致很多RxUI使用崩溃，本想试着改一下，可是太多了，不知道有没有什么好的方案。

**Comment by androidxu** [comment]
> 将gradle中的 maven { url 'https://esri.bintray.com/arcgis' }
> 改为
> maven{ url '[https://esri.jfrog.io/artifactory/arcgis'）](https://esri.jfrog.io/artifactory/arcgis'%EF%BC%89) }
> 
> 原因是这个网站（[https://esri.bintray.com/arcgis）用不了了](https://esri.bintray.com/arcgis%EF%BC%89%E7%94%A8%E4%B8%8D%E4%BA%86%E4%BA%86)

你发的我这边已经用不了，用这个吧
maven { url 'https://esri.jfrog.io/artifactory/arcgis' }

**Comment by Tamsiree** [comment]
前段时间挺忙的，现已解决
