### ISSUE TITLE
项目下下来运行报错  Type mismatch: inferred type is Context? but Context was expected

### ISSUE THREAD

**Issue by xichunjie** [Tamsiree/RxTool#276]
项目下下来，想跑一下，编译不过去，报：Type mismatch: inferred type is Context? but Context was expected  这个错，都是RxUI自定义控件构造函数报的错
![QQ截图20210604105322](https://user-images.githubusercontent.com/19978806/120739036-71e08980-c523-11eb-8360-5f3ce7ec65c9.png)

**Comment by Tamsiree** [comment]
谢谢告知，有段日子没折腾安卓了，最新commit已修复
