### ISSUE TITLE
本库是只作为一个工具为目标的吗

### ISSUE THREAD

**Issue by gt562559842** [Tamsiree/RxTool#287]
**Describe the bug**
因为我拉下来跑的时候，运行的时候遇到一些包错，比如：webview加载不出来（没支持http明文），拍照不成功（估计是权限的问题）、查看设备信息崩溃，我手机是鸿蒙的（正常应用都是兼容的），感觉其他人拉下来学习跑起来也会有点难受

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leijava** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sherrylou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Tamsiree** [comment]
本库旨在提供一些可参考的工具/例子，方便fork后自己拆解到需要的部分进行修改。

**Comment by leijava** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sherrylou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
