### ISSUE TITLE
RxcrashTool 使用的问题

### ISSUE THREAD

**Issue by budou1994** [Tamsiree/RxTool#50]
你好，对您这个类的使用有些费解，我在使用这个工具的时候，不小心在一个页面出现了逻辑错误，然后APP会自动弹出错误提示，并将APP关闭。但是我在日志之中并未发现我所错误的提示，是否是因为这个直接将日志过滤了一下，还是我的使用有些问题。就是想请教一下，这个类的使用的一些简单介绍，麻烦作者了。谢谢！

**Comment by Tamsiree** [comment]
已更新崩溃工具类，更新到最新版本试试
