### ISSUE TITLE
扫描二维码有bug

### ISSUE THREAD

**Issue by CorruptWood** [Tamsiree/RxTool#61]
![Uploading image.png…]
反复进入扫描二维码页面、退出，很快复现这个问题，Demo里面也能复现

**Comment by CorruptWood** [comment]
![qq 20171109172612](https://user-images.githubusercontent.com/26950355/32597934-36240132-c573-11e7-8452-4b5e72669b68.png)
![qq 20171109172633](https://user-images.githubusercontent.com/26950355/32597935-365e2c72-c573-11e7-96f3-025cd9112475.png)

**Comment by CorruptWood** [comment]
找到问题了。。。。
当扫描页面销毁了，activity.getHandler=null;,此时扫描解码有可能还没有完成，导致发送消息的时候出现了异常。

![qq 20171109174657](https://user-images.githubusercontent.com/26950355/32598952-053eb47e-c576-11e7-8b64-2eca23c70671.png)

我的解决方案：

  Handler handler = activity.getHandler();
        if (handler != null) {
            if (rawResult != null) {
                long end = System.currentTimeMillis();
                Log.d(TAG, "Found barcode (" + (end - start) + " ms):\n" + rawResult.toString());
                Message message = Message.obtain(handler, R.id.decode_succeeded, rawResult);
                Bundle bundle = new Bundle();
                bundle.putParcelable("barcode_bitmap", source.renderCroppedGreyscaleBitmap());
                message.setData(bundle);
                //Log.d(TAG, "Sending decode succeeded message...");
                message.sendToTarget();
            } else {
                Message message = Message.obtain(handler, R.id.decode_failed);
                message.sendToTarget();
            }
        }

**Comment by ChineseCodeFarmer** [comment]
![qq 20171109210951](https://user-images.githubusercontent.com/24244048/32607005-627e2bb2-c592-11e7-8833-e25fd8211d8a.png)
我来给出正确答案，在ActivityScanerCode的onPause中会调用quitSynchronously()这个方法，zxing的Androiddemo源码里面的这个方法是有我注释那几句的，作者的代码中没有我注释那几句就会造成线程没有停止而出现空指针。加上就Ok了

**Comment by helloworkcupid** [comment]
楼上方法可能解决了bug,但是问题是：依赖包为什么不解决这个bug 呢？噗。。。。
