### ISSUE TITLE
Rx指的是什么？

### ISSUE THREAD

**Issue by ddrandy** [Tamsiree/RxTool#95]
比较流行的项目中Rx一般指的是Reactive Extensions，中文即响应式扩展。
这个项目中我还没有发现Reactive的地方，个人认为项目名字叫RxTools有点不妥，
有诱导开发者之嫌。
作为工具库的话，要走得远，建议还是取个名副其实的名字。
ExTools也许更切题一些

**Comment by nekocode** [comment]
强烈建议改掉前缀。
你这名字，着实黑了一把 Rx 啊，。
