### ISSUE TITLE
为什么我的会报错

### ISSUE THREAD

**Issue by qczgwxg** [Tamsiree/RxTool#99]
Error:(28, 13) Failed to resolve: com.github.vondear:RxTools:v1.7.7.3
<a href="openFile:D:/Temp1654/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by kanfRUI** [comment]
我遇到这个问题，导不下来的，好奇怪。兄弟解决了没

**Comment by kanfRUI** [comment]
注意是加在这个allprojects 里面
allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}
